app = "telemination-game"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  BOT_TOKEN = "8003276937:AAH_3STTw5r2UBnzCGYjCtjpz3TEBrvDcf4"

[http_service]
  internal_port = 8080
  force_https = true
